
package br.edu.qi.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotaWsService", targetNamespace = "http://service.qi.edu.br/", wsdlLocation = "http://localhost:8080/notaWS?wsdl")
public class NotaWsService
    extends Service
{

    private final static URL NOTAWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTAWSSERVICE_EXCEPTION;
    private final static QName NOTAWSSERVICE_QNAME = new QName("http://service.qi.edu.br/", "NotaWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/notaWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTAWSSERVICE_WSDL_LOCATION = url;
        NOTAWSSERVICE_EXCEPTION = e;
    }

    public NotaWsService() {
        super(__getWsdlLocation(), NOTAWSSERVICE_QNAME);
    }

    public NotaWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTAWSSERVICE_QNAME, features);
    }

    public NotaWsService(URL wsdlLocation) {
        super(wsdlLocation, NOTAWSSERVICE_QNAME);
    }

    public NotaWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTAWSSERVICE_QNAME, features);
    }

    public NotaWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotaWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns INota
     */
    @WebEndpoint(name = "NotaWsPort")
    public INota getNotaWsPort() {
        return super.getPort(new QName("http://service.qi.edu.br/", "NotaWsPort"), INota.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns INota
     */
    @WebEndpoint(name = "NotaWsPort")
    public INota getNotaWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.qi.edu.br/", "NotaWsPort"), INota.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTAWSSERVICE_EXCEPTION!= null) {
            throw NOTAWSSERVICE_EXCEPTION;
        }
        return NOTAWSSERVICE_WSDL_LOCATION;
    }

}
